### ISSUE TITLE
State machine entry point for CS fmi3 

### ISSUE THREAD

**Issue by jbernalr** [APillekeit/fmi-standard#4]
Please excuse if this may have been discussed before or already clarifed, but in the current version of the state machine diagram for cs fmi3: /docs/images/calling-sequence-co-simulation.svg
shows the "event mode" as the entry point.
However if the `canHandleEarlyReturn` (maybe other new features as well) feature is set to false, how should an FMU transition into StepMode, which is the only mode for 2.0 Co-Simulation?
I see the following options:

- Option one: Change the default entry point to someone that is common to all co-simulation fmu types i.e.: default entry point for fmi3 cs would be step mode.
- Option two: add more than one state machines / behiaviours to the spec document
- Option three:  add an additional mode common to all cs fmu types?

There may be someone who is in favor of having a cs state machine similar to model exchange with event mode as entry point. but in this case what to do with fmi2 cs fmus?

![fmi3-cs-state-machine-entry-point](https://user-images.githubusercontent.com/33322694/59604065-5cda7800-910b-11e9-82c3-9e8bf0ef50a0.png)

**Comment by jph-tavella** [comment]
The question is relevant and the option two (have more than one state machine) is probably the worse.
I think there is another option with UML transitions because it is possible to define guards (Boolean expressions) dynamically evaluated in order to enable/disable transitions when they are evaluated to TRUE/FALSE.
The transition from InitializationMode to EventMode could then be conditionned by a guard [canHandleEarlyReturn]. This transition is then only possible when the Early Return feature is supported by the FMU.
To complete the state machine, a new transition from InitializationMode to StepMode is to be Added with the opposite guard condition [not(canHandleEarlyReturn)].

**Comment by jbernalr** [comment]
From the discussion in Renningen 2019, the following has been decided: 

- Hybrid Co-Simulation entry point after "Initialization Mode" is "Event Mode"
- Co-Simulation entrypoint after "Initialization Mode" is "Step Mode"
- Two state machines will be required
